
<h2 id="Linear-Algebra">Linear Algebra<a class="anchor-link" href="#Linear-Algebra">¶</a></h2><p>Linear Algebra is an important part of any array library. <code>numpy.linalg</code> module will be used for linear algebric operations. Some of commonly used Linear Algebra functions:</p>
<table>
<thead><tr>
<th style="text-align:left">Function</th>
<th style="text-align:left">Description   </th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"><code>np.dot</code></td>
<td style="text-align:left">Dot product of two arrays</td>
</tr>
<tr>
<td style="text-align:left"><code>np.vdot</code></td>
<td style="text-align:left">Returns the dot product of two vectors</td>
</tr>
<tr>
<td style="text-align:left"><code>linalg.multi_dot</code></td>
<td style="text-align:left">Compute the dot product of two or more arrays in a single function call</td>
</tr>
<tr>
<td style="text-align:left"><code>linalg.eig</code></td>
<td style="text-align:left">Compute the eigenvalues and eigenvectors of a square array</td>
</tr>
<tr>
<td style="text-align:left"><code>linalg.det</code></td>
<td style="text-align:left">Compute the matrix determinant</td>
</tr>
<tr>
<td style="text-align:left"><code>linalg.inv</code></td>
<td style="text-align:left">Compute inverse of a square matrix</td>
</tr>
<tr>
<td style="text-align:left"><code>linalg.solve</code></td>
<td style="text-align:left">Solve a linear matrix equation, or system of linear scalar equations.</td>
</tr>
</tbody>
</table>


In [1]:
# Import required libraries
import numpy as np

In [3]:
# Define a 2D array
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
b

array([[11, 12],
       [13, 14]])


<h3 id="dot">dot<a class="anchor-link" href="#dot">¶</a></h3><p>The dot product of two arrays.</p>


In [6]:
# dot Product
np.dot(a,b)

array([[37, 40],
       [85, 92]])


<p>a.dot(b) is equivalent to np.dot(a,b)</p>


In [7]:
a.dot(b)

array([[37, 40],
       [85, 92]])

In [8]:
# Verify output
[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

[[37, 40], [85, 92]]


<p>As of Python 3.5, the  <code>@</code> symbol also works as an infix operator that performs matrix multiplication.</p>


In [9]:
a @ np.ones(2)  # equal to a.dot(np.ones(2))

array([3., 7.])


<h3 id="vdot">vdot<a class="anchor-link" href="#vdot">¶</a></h3><p>The dot product of two vectors. <code>vdot</code> handles multidimensional arrays differently than dot: it does not perform a matrix product, but flattens input arguments to 1-D vectors first. Consequently, it should only be used for vectors.</p>


In [10]:
# vdot 
np.vdot(a,b)
# = 1*11 + 2*12 + 3*14 + 4*14

130

In [11]:
np.vdot(b, a)

130


Higher-dimensional arrays are flattened.



<h3 id="multi_dot">multi_dot<a class="anchor-link" href="#multi_dot">¶</a></h3><p>Computes the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order.</p>
<p><code>multi_dot</code> chains <code>numpy.dot</code></p>


In [12]:
from numpy.linalg import multi_dot

In [13]:
w = np.random.random((10000, 100))
x = np.random.random((100, 1000))
y = np.random.random((1000, 5))
z = np.random.random((5, 333))

In [14]:
# the actual dot multiplication
out_1 = multi_dot([w, x, y, z])
out_1

array([[31333.81624111, 24443.8393604 , 41636.36171362, ...,
        25915.70551868, 22707.24759683, 38830.41257437],
       [30446.11663099, 23750.64088189, 40451.92750304, ...,
        25184.49736836, 22060.79863393, 37727.15673927],
       [32939.90772266, 25693.82439782, 43772.88905566, ...,
        27247.04967461, 23869.17221373, 40826.21742857],
       ...,
       [30517.19138845, 23809.4644785 , 40548.90437754, ...,
        25248.65674863, 22112.03294442, 37799.44715978],
       [30952.71510925, 24143.0393545 , 41128.84403043, ...,
        25604.31446873, 22428.2411748 , 38356.53557846],
       [30881.08649553, 24089.58170356, 41043.55525583, ...,
        25537.98103077, 22382.02884429, 38285.43121988]])

In [15]:
# output shape
out_1.shape

(10000, 333)

In [16]:
# Same as above
out_2 = np.dot(np.dot(np.dot(w, x), y), z)
out_2.shape

(10000, 333)

In [18]:
# Same as above
out_3 = w.dot(x).dot(y).dot(z)
out_3.shape

(10000, 333)


<h3 id="eigen-values-and-vector">eigen values and vector<a class="anchor-link" href="#eigen-values-and-vector">¶</a></h3><p>Computes the eigenvalues and right eigenvectors of a square array.</p>


In [19]:
# Import Linear Algebra module from NumPy
from numpy import linalg as LA


<p>Let's create a diagonal matrix using <code>np.diag()</code> function in NumPy.</p>


In [20]:
dia = np.diag((2, 3, 4))
dia

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])


<p>Since our input array is a diagonal matrix, the eigen vectors make a identity matrix and the eigen values are simply the diagonal elements of the input matrix. Let's check this!</p>


In [21]:
# Derive eigen values and vectors
e_val,e_vec = LA.eig(dia)

In [22]:
# Eigen Values
e_val

array([2., 3., 4.])

In [23]:
# Eigne Vectors
e_vec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


<p>Another example</p>


In [24]:
# let A be the 2x2 square matrix
A = np.array([[3,-4], [2,-6]])

In [25]:
LA.eig(A) # calculates the eigen-values and eigen-vectors

(array([ 2., -5.]), array([[0.9701425 , 0.4472136 ],
        [0.24253563, 0.89442719]]))


<h3 id="determinant">determinant<a class="anchor-link" href="#determinant">¶</a></h3><p>Compute the determinant of an array.</p>


In [26]:
LA.det(A) # determinant of A

-10.000000000000002


<h3 id="inverse">inverse<a class="anchor-link" href="#inverse">¶</a></h3><p>Compute the inverse of a matrix.</p>


In [27]:
LA.inv(A) # inverse of A

array([[ 0.6, -0.4],
       [ 0.2, -0.3]])


<h3 id="solve">solve<a class="anchor-link" href="#solve">¶</a></h3><p>Before we get into the portfolio optimisation problem, let’s solve a set of linear equations using linalg.solve <br/><br/></p>
\begin{matrix}
2x+1y-2z &amp;=&amp;10  \ \\
3x+2y+2z &amp;=&amp;1 \ \\
5x+4y+3z &amp;=&amp;4 \ \\
\end{matrix}<p>Using the matrix inversion problem $A$<strong>x</strong>=<strong>b</strong> where,</p>
$$A=\left( 
\begin{array}{ccc}
2 &amp; 1 &amp; -2 \\ 
3 &amp; 2 &amp; 2 \\ 
5 &amp; 4 &amp; 3%
\end{array}%
\right) ;\ \mathbf{b=}\left( 
\begin{array}{c}
10 \\ 
1 \\ 
4%
\end{array}%
\right)$$<p></p>


In [28]:
A = np.array([[2,1,-2], [3,2,2], [5,4,3]])
b = np.array([10,1,4])

In [29]:
A

array([[ 2,  1, -2],
       [ 3,  2,  2],
       [ 5,  4,  3]])

In [30]:
b

array([10,  1,  4])

In [31]:
x = LA.solve(A,b)
x

array([ 1.,  2., -3.])


<p>Check that the solution is correct</p>


In [33]:
np.allclose(np.dot(A,x), b)

True


<h1 id="References">References<a class="anchor-link" href="#References">¶</a></h1><ul>
<li><p>Numpy linear algebra documentation <a href="https://numpy.org/doc/stable/reference/routines.linalg.html">https://numpy.org/doc/stable/reference/routines.linalg.html</a></p>
</li>
<li><p>Jake VanderPlas (2016), Python Data Science Handbook: Essential tools for working with data</p>
</li>
<li><p>McKinney (2018), Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython</p>
</li>
</ul>
